# https://docs.camunda.io/docs/apis-tools/spring-zeebe-sdk/getting-started/
# https://docs.camunda.io/docs/apis-tools/spring-zeebe-sdk/configuration/

camunda:
  client:
    mode: saas
    auth:
      client-id: Nm0.qCSDTuyxdoz5XH0IJN9ukmVYQGdt
      client-secret: f8cvfEz69owQJ03MNjQsHAZ1N86RP7yyV86NzJ5sis6syjIcYNKsL9SgbPt9ON7a
    cluster-id: c9a499c4-6479-49f5-9314-ef617abb3286
    region: bru-2

# go to http://localhost:8084/applications/ and create application of type M2M with read/write access to Operate & Tasklist
identity.clientId: pouet
identity.clientSecret: CSf4Jqwcmw6HsEocpslOvVPjZ4t8DUoP
keycloakUrl: http://localhost:18080
tasklistUrl: http://localhost:8082/
operateUrl: http://localhost:8081/

# this is to allow react application launched separately to access the WS
websocket:
  allowedOrigin: "*"

springdoc.swagger-ui.path: /swagger-ui.html

spring:
  servlet.multipart:
    max-file-size: 10MB
    max-request-size: 30MB

  security.oauth2:
    enabled: false

server:
  port: 8080
  error:
    whitelabel:
      enabled: false
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1048576

logging:
  level:
    root: INFO
